### ISSUE TITLE
Move tabs to the bottom of the window

### ISSUE THREAD

**Issue by porst17** [danielramosg/sphereofearth#1]
In exhibitions with large touch screens, children and sometimes also adults have problems reaching the tabs (and buttons in general) if the are located at the top of the window.

**Comment by danielramosg** [comment]
Partially done in https://github.com/danielramosg/sphereofearth/commit/9be085b1db2bf798fb5fcefbce04cadfeb474e87
Map projections tabs on the bottom, main functions on the top. I close this issue. What it is needed maybe is a general re-design of the interface, to be discussed in some other issue.
