### ISSUE TITLE
Add language switcher

### ISSUE THREAD

**Issue by porst17** [danielramosg/sphereofearth#14]
In mixed audience exhibitions (school classes + international scientists), it is necessary to switch the program language during runtime. Restarting is usually not a option:
1. it can break kiosk mode
2. you would need an external language switcher which is aware of all the languages available in a certain virtual exhibit

The recommended symbol for switching languages is http://fortawesome.github.io/Font-Awesome/icon/language/ or something similar.

**Comment by danielramosg** [comment]
Switch added. It changes the explanation texts (html files), but not yet the few words in the tabs, buttons and title.

**Comment by danielramosg** [comment]
Switch improved. Now it translates also the menues, buttons and title.

Pending the actual translations.

**Comment by porst17** [comment]
For reference: language switcher added in ea00beb438d86b43d075c94099ded6a59973893a and improved in e2acac1f898876434d4fc77b6495d23bd60c99f2.
