### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by HexeBianca** [danielramosg/sphereofearth#20]
I got the following error messages, which did not affect the use of the program, everything looked good.
![1](https://cloud.githubusercontent.com/assets/10153723/9668502/29a0c514-5282-11e5-8b40-d24ac387bb97.jpg)
When I noticed it, it was only the lines including btp = atan...
Then I played around trying to find out what it is, assuming it happend when a Tissot ellipse is attempted to be drawn at the poles. I clicked a couple of times near the poles and then the other lines showed up in the DOS shell window.

**Comment by HexeBianca** [comment]
here are more errors listed in the DOS shell window. The program worked fine.
![1](https://cloud.githubusercontent.com/assets/10153723/9721446/b989676a-559a-11e5-967b-7fd950262619.jpg)

**Comment by danielramosg** [comment]
Thanks, this is a known issue. As far as I can tell it is harmless (these are Warnings, not Errors), but I prefer not to hide the warnings, in case something important appears. I will re-examine the formulas to find the singular cases that raise exceptions. Low priority for now.

**Comment by danielramosg** [comment]
I found out that this was solved some time ago in https://github.com/danielramosg/sphereofearth/commit/b057e3a685ecfb7b16a8436c16bff92389d79d13. New errors in new issues.
