### ISSUE TITLE
Image on first tab appears aliased

### ISSUE THREAD

**Issue by porst17** [danielramosg/sphereofearth#4]
Depending on your screen resolution, the image on the first tab _What is a map?_ appears aliased. On my particular system, I can see gaps in the curved arrow below dF.

The best solution would probably be to replace the PNG image by an SVG image. The HTML rendering capabilities of Qt are able to render SVG pretty well. I actually tested it right now with https://upload.wikimedia.org/wikipedia/commons/b/b0/NewTux.svg instead of `df.png`. The TuX image is very similar to your drawing since it also has gradients in it.

The image looks like it has been created in LaTeX. So probably just export to PDF and then convert to SVG.

**Comment by danielramosg** [comment]
The image was created in Inkscape as SVG. It renders perfectly on Firefox, but not so well in the html renderer of Qt. Hence I just took a screenshot. Did you test the NewTux inside Qt?

**Comment by danielramosg** [comment]
Indeed, the svg rendering is not perfect in Qt: 
http://stackoverflow.com/questions/26326808/is-it-posible-to-display-svg-in-qt5-3-textedit-without-loosing-quality

It first rasterizes and then rescales. Furthermore, a simple path with an arrow (the arrow is a decoration) is not properly rendered (no arrow).

Still trying. Best option can still be a png with transparency.

**Comment by porst17** [comment]
I tested NewTux inside Qt (actually inside SOE by replacing the like in `intro.html`) and it looks like it does in Firefox. You probably have to bake the path decorations into the path in order to work with simple SVG implementations like Qt's. But I am just guessing. If you send me the PDF, I can take a look.

**Comment by danielramosg** [comment]
I "baked" the path decorations, and set the native resolution of the svg to 600px width. The intro.html renders at exactly 600px width, so now it is displayed properly (but no rescaling possible). Background is transparent.

The change is already pushed to the repo. I close the issue. :)
